"""
Batch 3 - 100 More Products for FinFind Sample Data
"""
import json
import uuid
from datetime import datetime, timedelta
from pathlib import Path
import random

BATCH3_PRODUCTS = [
    # ELECTRONICS - Computers & Accessories
    {
        "title": "ASUS ROG Strix Gaming Laptop",
        "description": "High-performance gaming laptop with RTX 4080, 32GB RAM, 1TB SSD, and 240Hz display for competitive gaming.",
        "category": "Electronics",
        "subcategory": "Laptops",
        "brand": "ASUS",
        "price": 2299.99,
        "original_price": 2599.99,
        "currency": "USD",
        "attributes": {"processor": "Intel i9-13900H", "ram": "32GB", "storage": "1TB SSD", "display": "17.3 inch 240Hz"},
        "image_url": "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 15,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["gaming", "laptop", "rtx4080", "high-performance", "esports"]
    },
    {
        "title": "Razer BlackWidow V4 Pro Keyboard",
        "description": "Premium mechanical gaming keyboard with RGB lighting, macro keys, and hot-swappable switches.",
        "category": "Electronics",
        "subcategory": "Keyboards",
        "brand": "Razer",
        "price": 229.99,
        "original_price": 249.99,
        "currency": "USD",
        "attributes": {"switch_type": "Green", "connectivity": "USB-C", "rgb": "Chroma RGB"},
        "image_url": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 45,
        "payment_options": ["full", "installment_3"],
        "tags": ["gaming", "keyboard", "mechanical", "rgb", "razer"]
    },
    {
        "title": "Logitech G Pro X Superlight Mouse",
        "description": "Ultra-lightweight wireless gaming mouse weighing only 63g with HERO 25K sensor for competitive gaming.",
        "category": "Electronics",
        "subcategory": "Mice",
        "brand": "Logitech",
        "price": 149.99,
        "original_price": 159.99,
        "currency": "USD",
        "attributes": {"weight": "63g", "sensor": "HERO 25K", "battery_life": "70 hours"},
        "image_url": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 80,
        "payment_options": ["full"],
        "tags": ["gaming", "mouse", "wireless", "lightweight", "esports"]
    },
    {
        "title": "Samsung 990 PRO 2TB NVMe SSD",
        "description": "Blazing fast PCIe 4.0 NVMe SSD with read speeds up to 7,450 MB/s for gaming and content creation.",
        "category": "Electronics",
        "subcategory": "Storage",
        "brand": "Samsung",
        "price": 179.99,
        "original_price": 229.99,
        "currency": "USD",
        "attributes": {"capacity": "2TB", "interface": "PCIe 4.0", "read_speed": "7450 MB/s"},
        "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 120,
        "payment_options": ["full"],
        "tags": ["ssd", "storage", "nvme", "fast", "samsung"]
    },
    {
        "title": "Corsair 32GB DDR5 RAM Kit",
        "description": "High-speed DDR5-6000 memory kit with RGB lighting for gaming and workstation builds.",
        "category": "Electronics",
        "subcategory": "Memory",
        "brand": "Corsair",
        "price": 144.99,
        "original_price": 169.99,
        "currency": "USD",
        "attributes": {"capacity": "32GB (2x16GB)", "speed": "DDR5-6000", "latency": "CL36"},
        "image_url": "https://images.unsplash.com/photo-1562976540-1502c2145186?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 65,
        "payment_options": ["full"],
        "tags": ["ram", "memory", "ddr5", "rgb", "gaming"]
    },
    {
        "title": "NVIDIA GeForce RTX 4070 Ti",
        "description": "High-performance graphics card for 4K gaming with ray tracing and DLSS 3 technology.",
        "category": "Electronics",
        "subcategory": "Graphics Cards",
        "brand": "NVIDIA",
        "price": 799.99,
        "original_price": 899.99,
        "currency": "USD",
        "attributes": {"vram": "12GB GDDR6X", "ray_tracing": "Yes", "power": "285W"},
        "image_url": "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 25,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["gpu", "graphics-card", "rtx", "gaming", "4k"]
    },
    {
        "title": "Elgato Stream Deck MK.2",
        "description": "Customizable LCD key pad for streamers with 15 programmable keys and instant actions.",
        "category": "Electronics",
        "subcategory": "Streaming",
        "brand": "Elgato",
        "price": 149.99,
        "original_price": 149.99,
        "currency": "USD",
        "attributes": {"keys": "15 LCD", "connectivity": "USB-C", "software": "Stream Deck Software"},
        "image_url": "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 55,
        "payment_options": ["full"],
        "tags": ["streaming", "content-creator", "lcd", "productivity", "elgato"]
    },
    {
        "title": "Blue Yeti X Professional Microphone",
        "description": "Premium USB condenser microphone with four capsules, LED metering, and Blue VO!CE effects.",
        "category": "Electronics",
        "subcategory": "Microphones",
        "brand": "Blue",
        "price": 169.99,
        "original_price": 199.99,
        "currency": "USD",
        "attributes": {"type": "Condenser", "pattern": "4-Pattern", "sample_rate": "48kHz/24-bit"},
        "image_url": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 40,
        "payment_options": ["full"],
        "tags": ["microphone", "streaming", "podcast", "usb", "recording"]
    },
    {
        "title": "Anker 737 Power Bank 24000mAh",
        "description": "Massive capacity portable charger with 140W output for laptops, tablets, and phones.",
        "category": "Electronics",
        "subcategory": "Power Banks",
        "brand": "Anker",
        "price": 149.99,
        "original_price": 169.99,
        "currency": "USD",
        "attributes": {"capacity": "24000mAh", "output": "140W", "ports": "USB-C + USB-A"},
        "image_url": "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 90,
        "payment_options": ["full"],
        "tags": ["power-bank", "portable-charger", "usb-c", "travel", "laptop"]
    },
    {
        "title": "Google Pixel 8 Pro",
        "description": "Flagship smartphone with Tensor G3 chip, 50MP camera, and 7 years of software updates.",
        "category": "Electronics",
        "subcategory": "Smartphones",
        "brand": "Google",
        "price": 999.00,
        "original_price": 999.00,
        "currency": "USD",
        "attributes": {"display": "6.7 inch LTPO OLED", "camera": "50MP", "storage": "256GB"},
        "image_url": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 35,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["smartphone", "android", "pixel", "camera", "google"]
    },
    # ELECTRONICS - Audio
    {
        "title": "Sennheiser HD 660S2 Headphones",
        "description": "Audiophile open-back headphones with precision drivers for studio-quality sound.",
        "category": "Electronics",
        "subcategory": "Headphones",
        "brand": "Sennheiser",
        "price": 499.95,
        "original_price": 599.95,
        "currency": "USD",
        "attributes": {"type": "Open-back", "impedance": "300Ω", "frequency": "8Hz-41.5kHz"},
        "image_url": "https://images.unsplash.com/photo-1545127398-14699f92334b?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 20,
        "payment_options": ["full", "installment_3"],
        "tags": ["headphones", "audiophile", "open-back", "hi-fi", "sennheiser"]
    },
    {
        "title": "Sonos Era 300 Speaker",
        "description": "Premium spatial audio speaker with Dolby Atmos support and room-filling sound.",
        "category": "Electronics",
        "subcategory": "Speakers",
        "brand": "Sonos",
        "price": 449.00,
        "original_price": 449.00,
        "currency": "USD",
        "attributes": {"audio": "Spatial Audio", "dolby_atmos": "Yes", "connectivity": "WiFi + Bluetooth"},
        "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 30,
        "payment_options": ["full", "installment_3"],
        "tags": ["speaker", "spatial-audio", "dolby-atmos", "smart-speaker", "sonos"]
    },
    {
        "title": "Shure SM7B Dynamic Microphone",
        "description": "Industry-standard vocal microphone used by podcasters and broadcasters worldwide.",
        "category": "Electronics",
        "subcategory": "Microphones",
        "brand": "Shure",
        "price": 399.00,
        "original_price": 399.00,
        "currency": "USD",
        "attributes": {"type": "Dynamic", "pattern": "Cardioid", "frequency": "50Hz-20kHz"},
        "image_url": "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 25,
        "payment_options": ["full", "installment_3"],
        "tags": ["microphone", "podcast", "broadcasting", "professional", "shure"]
    },
    {
        "title": "Jabra Elite 85t Earbuds",
        "description": "Premium true wireless earbuds with advanced ANC and customizable sound.",
        "category": "Electronics",
        "subcategory": "Earbuds",
        "brand": "Jabra",
        "price": 179.99,
        "original_price": 229.99,
        "currency": "USD",
        "attributes": {"anc": "Advanced ANC", "battery": "5.5 hours", "charging_case": "25 hours"},
        "image_url": "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 55,
        "payment_options": ["full"],
        "tags": ["earbuds", "wireless", "anc", "bluetooth", "jabra"]
    },
    {
        "title": "Audioengine A5+ Wireless Speakers",
        "description": "Premium powered bookshelf speakers with Bluetooth aptX HD for audiophile listening.",
        "category": "Electronics",
        "subcategory": "Speakers",
        "brand": "Audioengine",
        "price": 499.00,
        "original_price": 499.00,
        "currency": "USD",
        "attributes": {"power": "150W", "drivers": "5-inch Kevlar", "connectivity": "Bluetooth aptX HD"},
        "image_url": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 18,
        "payment_options": ["full", "installment_3"],
        "tags": ["speakers", "bookshelf", "audiophile", "bluetooth", "hi-fi"]
    },
    # FASHION - Men's Clothing
    {
        "title": "Levi's 501 Original Fit Jeans",
        "description": "Classic straight leg jeans with button fly and iconic styling since 1873.",
        "category": "Fashion",
        "subcategory": "Jeans",
        "brand": "Levi's",
        "price": 69.50,
        "original_price": 79.50,
        "currency": "USD",
        "attributes": {"fit": "Original Fit", "material": "100% Cotton", "closure": "Button Fly"},
        "image_url": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 150,
        "payment_options": ["full"],
        "tags": ["jeans", "denim", "classic", "men", "levis"]
    },
    {
        "title": "Ralph Lauren Polo Shirt",
        "description": "Classic fit cotton mesh polo shirt with embroidered pony logo.",
        "category": "Fashion",
        "subcategory": "Shirts",
        "brand": "Ralph Lauren",
        "price": 98.50,
        "original_price": 98.50,
        "currency": "USD",
        "attributes": {"fit": "Classic Fit", "material": "Cotton Mesh", "collar": "Polo Collar"},
        "image_url": "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 85,
        "payment_options": ["full"],
        "tags": ["polo", "shirt", "classic", "preppy", "ralph-lauren"]
    },
    {
        "title": "Canada Goose Expedition Parka",
        "description": "Extreme weather parka with Arctic Tech fabric and coyote fur trim hood.",
        "category": "Fashion",
        "subcategory": "Outerwear",
        "brand": "Canada Goose",
        "price": 1395.00,
        "original_price": 1395.00,
        "currency": "USD",
        "attributes": {"fill": "625 Fill Power Down", "temperature": "-30°C", "water_resistant": "Yes"},
        "image_url": "https://images.unsplash.com/photo-1544923246-77307dd628b5?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 12,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["parka", "winter", "extreme-cold", "luxury", "canada-goose"]
    },
    {
        "title": "Hugo Boss Slim Fit Suit",
        "description": "Modern slim fit wool suit in navy blue for business and formal occasions.",
        "category": "Fashion",
        "subcategory": "Suits",
        "brand": "Hugo Boss",
        "price": 795.00,
        "original_price": 895.00,
        "currency": "USD",
        "attributes": {"fit": "Slim Fit", "material": "Virgin Wool", "color": "Navy Blue"},
        "image_url": "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 20,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["suit", "formal", "business", "slim-fit", "hugo-boss"]
    },
    {
        "title": "Tommy Hilfiger Oxford Shirt",
        "description": "Classic button-down Oxford shirt with signature flag logo.",
        "category": "Fashion",
        "subcategory": "Shirts",
        "brand": "Tommy Hilfiger",
        "price": 79.50,
        "original_price": 89.50,
        "currency": "USD",
        "attributes": {"fit": "Regular Fit", "material": "Oxford Cotton", "collar": "Button-Down"},
        "image_url": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 70,
        "payment_options": ["full"],
        "tags": ["oxford", "shirt", "button-down", "classic", "tommy-hilfiger"]
    },
    # FASHION - Women's Clothing
    {
        "title": "Zara Flowing Midi Dress",
        "description": "Elegant flowing midi dress with floral print and adjustable tie waist.",
        "category": "Fashion",
        "subcategory": "Dresses",
        "brand": "Zara",
        "price": 69.90,
        "original_price": 89.90,
        "currency": "USD",
        "attributes": {"length": "Midi", "pattern": "Floral", "material": "Viscose"},
        "image_url": "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 45,
        "payment_options": ["full"],
        "tags": ["dress", "midi", "floral", "elegant", "zara"]
    },
    {
        "title": "Lululemon Align High-Rise Leggings",
        "description": "Buttery soft Nulu fabric leggings with high-rise waist for yoga and everyday wear.",
        "category": "Fashion",
        "subcategory": "Activewear",
        "brand": "Lululemon",
        "price": 98.00,
        "original_price": 98.00,
        "currency": "USD",
        "attributes": {"rise": "High-Rise", "length": "28 inch", "material": "Nulu Fabric"},
        "image_url": "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 100,
        "payment_options": ["full"],
        "tags": ["leggings", "yoga", "activewear", "high-rise", "lululemon"]
    },
    {
        "title": "Michael Kors Leather Tote Bag",
        "description": "Spacious saffiano leather tote with laptop compartment and gold hardware.",
        "category": "Fashion",
        "subcategory": "Bags",
        "brand": "Michael Kors",
        "price": 298.00,
        "original_price": 358.00,
        "currency": "USD",
        "attributes": {"material": "Saffiano Leather", "size": "Large", "closure": "Zip Top"},
        "image_url": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 35,
        "payment_options": ["full", "installment_3"],
        "tags": ["tote", "bag", "leather", "designer", "michael-kors"]
    },
    {
        "title": "Stuart Weitzman Heeled Sandals",
        "description": "Elegant block heel sandals with ankle strap in patent leather.",
        "category": "Fashion",
        "subcategory": "Heels",
        "brand": "Stuart Weitzman",
        "price": 395.00,
        "original_price": 450.00,
        "currency": "USD",
        "attributes": {"heel_height": "3.5 inches", "material": "Patent Leather", "closure": "Ankle Strap"},
        "image_url": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 25,
        "payment_options": ["full", "installment_3"],
        "tags": ["heels", "sandals", "designer", "elegant", "stuart-weitzman"]
    },
    {
        "title": "Free People Oversized Cardigan",
        "description": "Cozy oversized knit cardigan with pockets and relaxed fit.",
        "category": "Fashion",
        "subcategory": "Sweaters",
        "brand": "Free People",
        "price": 148.00,
        "original_price": 168.00,
        "currency": "USD",
        "attributes": {"fit": "Oversized", "material": "Cotton Blend", "length": "Long"},
        "image_url": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 40,
        "payment_options": ["full"],
        "tags": ["cardigan", "oversized", "cozy", "knitwear", "free-people"]
    },
    # FASHION - Footwear
    {
        "title": "New Balance 990v6 Sneakers",
        "description": "Premium Made in USA running shoes with ENCAP midsole cushioning.",
        "category": "Fashion",
        "subcategory": "Sneakers",
        "brand": "New Balance",
        "price": 199.99,
        "original_price": 199.99,
        "currency": "USD",
        "attributes": {"made_in": "USA", "cushioning": "ENCAP", "upper": "Pigskin Suede + Mesh"},
        "image_url": "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 60,
        "payment_options": ["full"],
        "tags": ["sneakers", "running", "made-in-usa", "premium", "new-balance"]
    },
    {
        "title": "Dr. Martens 1460 Boots",
        "description": "Iconic 8-eye leather boots with air-cushioned sole and yellow stitching.",
        "category": "Fashion",
        "subcategory": "Boots",
        "brand": "Dr. Martens",
        "price": 180.00,
        "original_price": 180.00,
        "currency": "USD",
        "attributes": {"material": "Smooth Leather", "sole": "Air-Cushioned", "height": "8-Eye"},
        "image_url": "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 55,
        "payment_options": ["full"],
        "tags": ["boots", "leather", "iconic", "punk", "dr-martens"]
    },
    {
        "title": "Birkenstock Arizona Sandals",
        "description": "Classic two-strap sandals with contoured cork footbed and suede lining.",
        "category": "Fashion",
        "subcategory": "Sandals",
        "brand": "Birkenstock",
        "price": 110.00,
        "original_price": 110.00,
        "currency": "USD",
        "attributes": {"material": "Birko-Flor", "footbed": "Cork", "straps": "Adjustable"},
        "image_url": "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 80,
        "payment_options": ["full"],
        "tags": ["sandals", "comfortable", "classic", "summer", "birkenstock"]
    },
    {
        "title": "Vans Old Skool Skate Shoes",
        "description": "Classic skate shoes with signature side stripe and padded collar.",
        "category": "Fashion",
        "subcategory": "Sneakers",
        "brand": "Vans",
        "price": 70.00,
        "original_price": 70.00,
        "currency": "USD",
        "attributes": {"material": "Canvas + Suede", "sole": "Vulcanized Rubber", "style": "Low Top"},
        "image_url": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 120,
        "payment_options": ["full"],
        "tags": ["sneakers", "skate", "classic", "casual", "vans"]
    },
    {
        "title": "Cole Haan GrandPro Tennis Sneakers",
        "description": "Lightweight leather tennis sneakers with Grand.OS cushioning technology.",
        "category": "Fashion",
        "subcategory": "Sneakers",
        "brand": "Cole Haan",
        "price": 150.00,
        "original_price": 170.00,
        "currency": "USD",
        "attributes": {"material": "Leather", "technology": "Grand.OS", "style": "Tennis"},
        "image_url": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 45,
        "payment_options": ["full"],
        "tags": ["sneakers", "leather", "tennis", "comfortable", "cole-haan"]
    },
    # HOME & KITCHEN - Appliances
    {
        "title": "KitchenAid Artisan Stand Mixer",
        "description": "Iconic tilt-head stand mixer with 5-quart bowl and 10 speeds for baking enthusiasts.",
        "category": "Home & Kitchen",
        "subcategory": "Appliances",
        "brand": "KitchenAid",
        "price": 449.99,
        "original_price": 499.99,
        "currency": "USD",
        "attributes": {"capacity": "5 Quart", "power": "325W", "speeds": "10"},
        "image_url": "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 30,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["stand-mixer", "baking", "kitchen", "artisan", "kitchenaid"]
    },
    {
        "title": "Vitamix A3500 Blender",
        "description": "Professional-grade smart blender with touchscreen, self-detect containers, and 5 programs.",
        "category": "Home & Kitchen",
        "subcategory": "Appliances",
        "brand": "Vitamix",
        "price": 649.95,
        "original_price": 699.95,
        "currency": "USD",
        "attributes": {"motor": "2.2 HP", "programs": "5", "container": "64 oz"},
        "image_url": "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 22,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["blender", "professional", "smart", "smoothie", "vitamix"]
    },
    {
        "title": "Breville Barista Express Espresso Machine",
        "description": "All-in-one espresso machine with integrated grinder and precise extraction.",
        "category": "Home & Kitchen",
        "subcategory": "Coffee Makers",
        "brand": "Breville",
        "price": 749.95,
        "original_price": 849.95,
        "currency": "USD",
        "attributes": {"grinder": "Integrated Burr", "pressure": "15 Bar", "capacity": "67 oz"},
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 18,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["espresso", "coffee", "barista", "grinder", "breville"]
    },
    {
        "title": "Ninja Foodi Smart XL Grill",
        "description": "6-in-1 indoor smart grill with smart thermometer for perfect results every time.",
        "category": "Home & Kitchen",
        "subcategory": "Appliances",
        "brand": "Ninja",
        "price": 279.99,
        "original_price": 329.99,
        "currency": "USD",
        "attributes": {"functions": "6-in-1", "capacity": "XL", "smart_thermometer": "Yes"},
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 40,
        "payment_options": ["full", "installment_3"],
        "tags": ["grill", "indoor", "smart", "air-fryer", "ninja"]
    },
    {
        "title": "Dyson V15 Detect Vacuum",
        "description": "Cordless vacuum with laser dust detection, LCD screen, and HEPA filtration.",
        "category": "Home & Kitchen",
        "subcategory": "Vacuums",
        "brand": "Dyson",
        "price": 749.99,
        "original_price": 749.99,
        "currency": "USD",
        "attributes": {"runtime": "60 minutes", "dust_detection": "Laser", "filtration": "HEPA"},
        "image_url": "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 25,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["vacuum", "cordless", "laser", "hepa", "dyson"]
    },
    # HOME & KITCHEN - Cookware
    {
        "title": "Le Creuset Dutch Oven 5.5 Qt",
        "description": "Iconic enameled cast iron Dutch oven for braising, baking, and slow cooking.",
        "category": "Home & Kitchen",
        "subcategory": "Cookware",
        "brand": "Le Creuset",
        "price": 419.95,
        "original_price": 419.95,
        "currency": "USD",
        "attributes": {"capacity": "5.5 Quart", "material": "Enameled Cast Iron", "oven_safe": "500°F"},
        "image_url": "https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 35,
        "payment_options": ["full", "installment_3"],
        "tags": ["dutch-oven", "cast-iron", "braising", "premium", "le-creuset"]
    },
    {
        "title": "All-Clad D5 Stainless Steel Pan Set",
        "description": "10-piece professional cookware set with 5-ply bonded construction.",
        "category": "Home & Kitchen",
        "subcategory": "Cookware",
        "brand": "All-Clad",
        "price": 849.99,
        "original_price": 999.99,
        "currency": "USD",
        "attributes": {"pieces": "10", "material": "5-Ply Stainless Steel", "oven_safe": "600°F"},
        "image_url": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 15,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["cookware-set", "stainless-steel", "professional", "premium", "all-clad"]
    },
    {
        "title": "Staub Cast Iron Cocotte",
        "description": "French-made cast iron cocotte with self-basting lid spikes for moist cooking.",
        "category": "Home & Kitchen",
        "subcategory": "Cookware",
        "brand": "Staub",
        "price": 379.99,
        "original_price": 399.99,
        "currency": "USD",
        "attributes": {"capacity": "5.5 Quart", "material": "Cast Iron", "made_in": "France"},
        "image_url": "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 28,
        "payment_options": ["full", "installment_3"],
        "tags": ["cocotte", "cast-iron", "french", "braising", "staub"]
    },
    {
        "title": "GreenPan Valencia Pro Ceramic Set",
        "description": "11-piece healthy ceramic nonstick cookware set with hard anodized body.",
        "category": "Home & Kitchen",
        "subcategory": "Cookware",
        "brand": "GreenPan",
        "price": 449.99,
        "original_price": 549.99,
        "currency": "USD",
        "attributes": {"pieces": "11", "coating": "Thermolon Ceramic", "pfoa_free": "Yes"},
        "image_url": "https://images.unsplash.com/photo-1584990347449-a6d1c5f0ddbc?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 32,
        "payment_options": ["full", "installment_3"],
        "tags": ["cookware-set", "ceramic", "nonstick", "healthy", "greenpan"]
    },
    {
        "title": "Wüsthof Classic Chef's Knife 8-inch",
        "description": "German-made precision forged chef's knife with full tang and triple-riveted handle.",
        "category": "Home & Kitchen",
        "subcategory": "Cutlery",
        "brand": "Wüsthof",
        "price": 175.00,
        "original_price": 195.00,
        "currency": "USD",
        "attributes": {"length": "8 inches", "material": "High Carbon Steel", "made_in": "Germany"},
        "image_url": "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 45,
        "payment_options": ["full"],
        "tags": ["knife", "chef-knife", "german", "forged", "wusthof"]
    },
    # HOME & KITCHEN - Furniture & Decor
    {
        "title": "Herman Miller Aeron Chair",
        "description": "Iconic ergonomic office chair with PostureFit SL and 8Z Pellicle suspension.",
        "category": "Home & Kitchen",
        "subcategory": "Furniture",
        "brand": "Herman Miller",
        "price": 1395.00,
        "original_price": 1545.00,
        "currency": "USD",
        "attributes": {"size": "Size B", "material": "8Z Pellicle", "warranty": "12 Years"},
        "image_url": "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 12,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["chair", "ergonomic", "office", "premium", "herman-miller"]
    },
    {
        "title": "West Elm Mid-Century Nightstand",
        "description": "Modern nightstand in walnut finish with tapered legs and brass hardware.",
        "category": "Home & Kitchen",
        "subcategory": "Furniture",
        "brand": "West Elm",
        "price": 399.00,
        "original_price": 449.00,
        "currency": "USD",
        "attributes": {"finish": "Walnut", "dimensions": "22x18x24 inches", "drawers": "2"},
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 25,
        "payment_options": ["full", "installment_3"],
        "tags": ["nightstand", "mid-century", "walnut", "bedroom", "west-elm"]
    },
    {
        "title": "Crate & Barrel Axis Sofa",
        "description": "Classic low-profile sofa with bench cushion and down-blend filling.",
        "category": "Home & Kitchen",
        "subcategory": "Furniture",
        "brand": "Crate & Barrel",
        "price": 2199.00,
        "original_price": 2499.00,
        "currency": "USD",
        "attributes": {"length": "89 inches", "filling": "Down-Blend", "fabric": "Performance Fabric"},
        "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 8,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["sofa", "living-room", "down-blend", "modern", "crate-barrel"]
    },
    {
        "title": "IKEA KALLAX Shelf Unit",
        "description": "Versatile 4x4 cube storage unit perfect for books, decor, and organization.",
        "category": "Home & Kitchen",
        "subcategory": "Storage",
        "brand": "IKEA",
        "price": 179.00,
        "original_price": 179.00,
        "currency": "USD",
        "attributes": {"dimensions": "57.75x57.75 inches", "cubes": "16", "material": "Particleboard"},
        "image_url": "https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 50,
        "payment_options": ["full"],
        "tags": ["shelf", "storage", "cube", "organization", "ikea"]
    },
    {
        "title": "Pottery Barn Faux Fur Throw",
        "description": "Luxuriously soft faux fur throw blanket for couch or bed.",
        "category": "Home & Kitchen",
        "subcategory": "Bedding",
        "brand": "Pottery Barn",
        "price": 129.00,
        "original_price": 149.00,
        "currency": "USD",
        "attributes": {"size": "50x60 inches", "material": "Faux Fur", "backing": "Fleece"},
        "image_url": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 65,
        "payment_options": ["full"],
        "tags": ["throw", "blanket", "faux-fur", "cozy", "pottery-barn"]
    },
    # BEAUTY & PERSONAL CARE - Skincare
    {
        "title": "La Mer Crème de la Mer",
        "description": "Legendary moisturizing cream with Miracle Broth for deep hydration and renewal.",
        "category": "Beauty & Personal Care",
        "subcategory": "Skincare",
        "brand": "La Mer",
        "price": 380.00,
        "original_price": 380.00,
        "currency": "USD",
        "attributes": {"size": "2 oz", "skin_type": "All Skin Types", "benefits": "Hydration + Renewal"},
        "image_url": "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 30,
        "payment_options": ["full", "installment_3"],
        "tags": ["moisturizer", "luxury", "anti-aging", "hydration", "la-mer"]
    },
    {
        "title": "Drunk Elephant C-Firma Vitamin C Serum",
        "description": "Potent vitamin C day serum with ferulic acid and vitamin E for brighter skin.",
        "category": "Beauty & Personal Care",
        "subcategory": "Skincare",
        "brand": "Drunk Elephant",
        "price": 80.00,
        "original_price": 80.00,
        "currency": "USD",
        "attributes": {"size": "1 oz", "key_ingredient": "15% L-Ascorbic Acid", "skin_type": "All"},
        "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 55,
        "payment_options": ["full"],
        "tags": ["serum", "vitamin-c", "brightening", "antioxidant", "drunk-elephant"]
    },
    {
        "title": "Tatcha Dewy Skin Cream",
        "description": "Rich moisturizer with Japanese purple rice for plump, dewy skin.",
        "category": "Beauty & Personal Care",
        "subcategory": "Skincare",
        "brand": "Tatcha",
        "price": 69.00,
        "original_price": 69.00,
        "currency": "USD",
        "attributes": {"size": "1.7 oz", "skin_type": "Dry + Normal", "finish": "Dewy"},
        "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 48,
        "payment_options": ["full"],
        "tags": ["moisturizer", "dewy", "japanese", "hydrating", "tatcha"]
    },
    {
        "title": "Paula's Choice 2% BHA Exfoliant",
        "description": "Cult-favorite liquid exfoliant with salicylic acid for clear, smooth skin.",
        "category": "Beauty & Personal Care",
        "subcategory": "Skincare",
        "brand": "Paula's Choice",
        "price": 35.00,
        "original_price": 35.00,
        "currency": "USD",
        "attributes": {"size": "4 oz", "key_ingredient": "2% Salicylic Acid", "skin_type": "All"},
        "image_url": "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 90,
        "payment_options": ["full"],
        "tags": ["exfoliant", "bha", "salicylic-acid", "pores", "paulas-choice"]
    },
    {
        "title": "Sunday Riley Good Genes Lactic Acid",
        "description": "All-in-one lactic acid treatment for instant radiance and improved texture.",
        "category": "Beauty & Personal Care",
        "subcategory": "Skincare",
        "brand": "Sunday Riley",
        "price": 122.00,
        "original_price": 122.00,
        "currency": "USD",
        "attributes": {"size": "1 oz", "key_ingredient": "Lactic Acid", "benefits": "Radiance + Texture"},
        "image_url": "https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 38,
        "payment_options": ["full"],
        "tags": ["treatment", "lactic-acid", "radiance", "exfoliating", "sunday-riley"]
    },
    # BEAUTY & PERSONAL CARE - Makeup & Hair
    {
        "title": "Charlotte Tilbury Pillow Talk Lipstick",
        "description": "Iconic matte revolution lipstick in the universally flattering nude-pink shade.",
        "category": "Beauty & Personal Care",
        "subcategory": "Makeup",
        "brand": "Charlotte Tilbury",
        "price": 34.00,
        "original_price": 34.00,
        "currency": "USD",
        "attributes": {"finish": "Matte", "shade": "Pillow Talk", "formula": "Long-Wearing"},
        "image_url": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 75,
        "payment_options": ["full"],
        "tags": ["lipstick", "matte", "nude-pink", "iconic", "charlotte-tilbury"]
    },
    {
        "title": "Dyson Airwrap Complete",
        "description": "Multi-styler that curls, waves, smooths and dries with no extreme heat.",
        "category": "Beauty & Personal Care",
        "subcategory": "Hair Tools",
        "brand": "Dyson",
        "price": 599.99,
        "original_price": 599.99,
        "currency": "USD",
        "attributes": {"attachments": "6", "technology": "Coanda Effect", "heat_settings": "3"},
        "image_url": "https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 20,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["hair-styler", "curler", "dryer", "no-heat-damage", "dyson"]
    },
    {
        "title": "NARS Radiant Creamy Concealer",
        "description": "Award-winning concealer with buildable medium to full coverage.",
        "category": "Beauty & Personal Care",
        "subcategory": "Makeup",
        "brand": "NARS",
        "price": 32.00,
        "original_price": 32.00,
        "currency": "USD",
        "attributes": {"coverage": "Medium-Full", "finish": "Natural", "shades": "30+"},
        "image_url": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 85,
        "payment_options": ["full"],
        "tags": ["concealer", "creamy", "buildable", "award-winning", "nars"]
    },
    {
        "title": "Olaplex No. 3 Hair Perfector",
        "description": "At-home bond building treatment to repair and strengthen damaged hair.",
        "category": "Beauty & Personal Care",
        "subcategory": "Hair Care",
        "brand": "Olaplex",
        "price": 30.00,
        "original_price": 30.00,
        "currency": "USD",
        "attributes": {"size": "3.3 oz", "treatment_type": "Bond Building", "hair_type": "All"},
        "image_url": "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 100,
        "payment_options": ["full"],
        "tags": ["hair-treatment", "bond-repair", "damaged-hair", "strengthening", "olaplex"]
    },
    {
        "title": "Rare Beauty Soft Pinch Liquid Blush",
        "description": "Weightless liquid blush that blends seamlessly for a natural flush.",
        "category": "Beauty & Personal Care",
        "subcategory": "Makeup",
        "brand": "Rare Beauty",
        "price": 23.00,
        "original_price": 23.00,
        "currency": "USD",
        "attributes": {"finish": "Soft Matte + Dewy", "formula": "Long-Wearing", "size": "0.25 oz"},
        "image_url": "https://images.unsplash.com/photo-1503236823255-94609f598e71?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 70,
        "payment_options": ["full"],
        "tags": ["blush", "liquid", "natural", "long-wearing", "rare-beauty"]
    },
    # SPORTS & FITNESS
    {
        "title": "Peloton Bike+",
        "description": "Premium smart exercise bike with rotating 23.8 inch HD touchscreen.",
        "category": "Sports & Fitness",
        "subcategory": "Cardio Equipment",
        "brand": "Peloton",
        "price": 2495.00,
        "original_price": 2495.00,
        "currency": "USD",
        "attributes": {"screen": "23.8 inch HD", "resistance": "Auto-Follow", "speakers": "4-Channel"},
        "image_url": "https://images.unsplash.com/photo-1591291621164-2c6367723315?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 10,
        "payment_options": ["full", "installment_12", "installment_24"],
        "tags": ["exercise-bike", "smart", "connected-fitness", "cardio", "peloton"]
    },
    {
        "title": "Theragun Pro Massage Device",
        "description": "Professional-grade percussive therapy device with adjustable arm and OLED screen.",
        "category": "Sports & Fitness",
        "subcategory": "Recovery",
        "brand": "Therabody",
        "price": 599.00,
        "original_price": 599.00,
        "currency": "USD",
        "attributes": {"force": "60 lbs", "speeds": "5", "battery_life": "300 minutes"},
        "image_url": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 35,
        "payment_options": ["full", "installment_3"],
        "tags": ["massage", "recovery", "percussive", "muscle", "theragun"]
    },
    {
        "title": "Bowflex SelectTech 552 Dumbbells",
        "description": "Adjustable dumbbells replacing 15 sets of weights from 5-52.5 lbs.",
        "category": "Sports & Fitness",
        "subcategory": "Strength Training",
        "brand": "Bowflex",
        "price": 429.00,
        "original_price": 549.00,
        "currency": "USD",
        "attributes": {"weight_range": "5-52.5 lbs", "adjustments": "15 Settings", "type": "Pair"},
        "image_url": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 25,
        "payment_options": ["full", "installment_3"],
        "tags": ["dumbbells", "adjustable", "strength", "home-gym", "bowflex"]
    },
    {
        "title": "Manduka PRO Yoga Mat",
        "description": "Professional 6mm yoga mat with lifetime guarantee and closed-cell surface.",
        "category": "Sports & Fitness",
        "subcategory": "Yoga",
        "brand": "Manduka",
        "price": 130.00,
        "original_price": 130.00,
        "currency": "USD",
        "attributes": {"thickness": "6mm", "length": "71 inches", "material": "PVC"},
        "image_url": "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 60,
        "payment_options": ["full"],
        "tags": ["yoga-mat", "professional", "thick", "durable", "manduka"]
    },
    {
        "title": "Garmin Forerunner 965 Watch",
        "description": "Premium GPS running smartwatch with AMOLED display and advanced training metrics.",
        "category": "Sports & Fitness",
        "subcategory": "Smartwatches",
        "brand": "Garmin",
        "price": 599.99,
        "original_price": 599.99,
        "currency": "USD",
        "attributes": {"display": "AMOLED", "battery": "23 days", "gps": "Multi-Band"},
        "image_url": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 28,
        "payment_options": ["full", "installment_3"],
        "tags": ["smartwatch", "running", "gps", "training", "garmin"]
    },
    {
        "title": "NordicTrack Commercial 1750 Treadmill",
        "description": "Commercial-grade treadmill with 14 inch touchscreen and iFIT integration.",
        "category": "Sports & Fitness",
        "subcategory": "Cardio Equipment",
        "brand": "NordicTrack",
        "price": 1999.00,
        "original_price": 2499.00,
        "currency": "USD",
        "attributes": {"motor": "3.75 CHP", "incline": "-3% to 15%", "screen": "14 inch HD"},
        "image_url": "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 8,
        "payment_options": ["full", "installment_12", "installment_24"],
        "tags": ["treadmill", "commercial", "smart", "ifit", "nordictrack"]
    },
    {
        "title": "Hyperice Hypervolt 2 Pro",
        "description": "Powerful percussion massage gun with QuietGlide technology and 5 head attachments.",
        "category": "Sports & Fitness",
        "subcategory": "Recovery",
        "brand": "Hyperice",
        "price": 329.00,
        "original_price": 349.00,
        "currency": "USD",
        "attributes": {"speeds": "5", "attachments": "5", "battery": "3+ hours"},
        "image_url": "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 45,
        "payment_options": ["full"],
        "tags": ["massage-gun", "percussion", "recovery", "muscle", "hyperice"]
    },
    {
        "title": "TRX Pro4 Suspension Trainer",
        "description": "Professional suspension training system for full-body workouts anywhere.",
        "category": "Sports & Fitness",
        "subcategory": "Strength Training",
        "brand": "TRX",
        "price": 249.95,
        "original_price": 269.95,
        "currency": "USD",
        "attributes": {"weight_capacity": "350 lbs", "includes": "Indoor/Outdoor Anchors", "warranty": "Lifetime"},
        "image_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 40,
        "payment_options": ["full"],
        "tags": ["suspension", "bodyweight", "portable", "full-body", "trx"]
    },
    {
        "title": "Hydrow Rowing Machine",
        "description": "Connected rowing machine with 22 inch HD screen and live outdoor reality workouts.",
        "category": "Sports & Fitness",
        "subcategory": "Cardio Equipment",
        "brand": "Hydrow",
        "price": 2495.00,
        "original_price": 2495.00,
        "currency": "USD",
        "attributes": {"screen": "22 inch HD", "resistance": "Electromagnetic", "footprint": "86x25 inches"},
        "image_url": "https://images.unsplash.com/photo-1519505907962-0a6cb0167c73?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 6,
        "payment_options": ["full", "installment_12", "installment_24"],
        "tags": ["rowing", "connected-fitness", "cardio", "low-impact", "hydrow"]
    },
    {
        "title": "WHOOP 4.0 Fitness Tracker",
        "description": "Wearable health and fitness tracker with strain, recovery, and sleep coaching.",
        "category": "Sports & Fitness",
        "subcategory": "Wearables",
        "brand": "WHOOP",
        "price": 239.00,
        "original_price": 239.00,
        "currency": "USD",
        "attributes": {"sensors": "5", "battery": "5 days", "water_resistant": "IP68"},
        "image_url": "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 50,
        "payment_options": ["full"],
        "tags": ["fitness-tracker", "recovery", "sleep", "hrv", "whoop"]
    },
    # BOOKS & MEDIA
    {
        "title": "Atomic Habits by James Clear",
        "description": "The #1 New York Times bestseller on building good habits and breaking bad ones.",
        "category": "Books & Media",
        "subcategory": "Self-Help",
        "brand": "Avery Publishing",
        "price": 18.99,
        "original_price": 27.00,
        "currency": "USD",
        "attributes": {"format": "Hardcover", "pages": "320", "language": "English"},
        "image_url": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 200,
        "payment_options": ["full"],
        "tags": ["book", "self-help", "habits", "bestseller", "productivity"]
    },
    {
        "title": "The Psychology of Money",
        "description": "Morgan Housel's timeless lessons on wealth, greed, and happiness.",
        "category": "Books & Media",
        "subcategory": "Finance",
        "brand": "Harriman House",
        "price": 16.99,
        "original_price": 19.99,
        "currency": "USD",
        "attributes": {"format": "Paperback", "pages": "256", "language": "English"},
        "image_url": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 150,
        "payment_options": ["full"],
        "tags": ["book", "finance", "money", "investing", "psychology"]
    },
    {
        "title": "Project Hail Mary by Andy Weir",
        "description": "Epic sci-fi adventure from the author of The Martian about saving humanity.",
        "category": "Books & Media",
        "subcategory": "Science Fiction",
        "brand": "Ballantine Books",
        "price": 17.99,
        "original_price": 28.99,
        "currency": "USD",
        "attributes": {"format": "Hardcover", "pages": "496", "language": "English"},
        "image_url": "https://images.unsplash.com/photo-1518744386442-2d48ac47a7eb?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 120,
        "payment_options": ["full"],
        "tags": ["book", "science-fiction", "space", "adventure", "andy-weir"]
    },
    {
        "title": "Kindle Paperwhite Signature Edition",
        "description": "Premium e-reader with 6.8 inch display, wireless charging, and 32GB storage.",
        "category": "Books & Media",
        "subcategory": "E-Readers",
        "brand": "Amazon",
        "price": 189.99,
        "original_price": 189.99,
        "currency": "USD",
        "attributes": {"display": "6.8 inch 300ppi", "storage": "32GB", "battery": "10 weeks"},
        "image_url": "https://images.unsplash.com/photo-1592496001020-d31bd830651f?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 75,
        "payment_options": ["full"],
        "tags": ["e-reader", "kindle", "reading", "wireless-charging", "amazon"]
    },
    {
        "title": "The Creative Act by Rick Rubin",
        "description": "Legendary music producer's philosophy on creativity and the artistic process.",
        "category": "Books & Media",
        "subcategory": "Art & Creativity",
        "brand": "Penguin Press",
        "price": 26.99,
        "original_price": 32.00,
        "currency": "USD",
        "attributes": {"format": "Hardcover", "pages": "432", "language": "English"},
        "image_url": "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 90,
        "payment_options": ["full"],
        "tags": ["book", "creativity", "art", "music", "rick-rubin"]
    },
    {
        "title": "Apple AirPods Max",
        "description": "Premium over-ear headphones with spatial audio and computational audio.",
        "category": "Electronics",
        "subcategory": "Headphones",
        "brand": "Apple",
        "price": 549.00,
        "original_price": 549.00,
        "currency": "USD",
        "attributes": {"driver": "40mm", "anc": "Active Noise Cancellation", "battery": "20 hours"},
        "image_url": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 25,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["headphones", "over-ear", "spatial-audio", "anc", "apple"]
    },
    {
        "title": "Samsung Galaxy Tab S9 Ultra",
        "description": "Premium 14.6 inch Android tablet with S Pen and AMOLED display.",
        "category": "Electronics",
        "subcategory": "Tablets",
        "brand": "Samsung",
        "price": 1199.99,
        "original_price": 1199.99,
        "currency": "USD",
        "attributes": {"display": "14.6 inch AMOLED", "storage": "256GB", "s_pen": "Included"},
        "image_url": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 20,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["tablet", "android", "s-pen", "amoled", "samsung"]
    },
    {
        "title": "Sony PlayStation 5 Console",
        "description": "Next-gen gaming console with 4K gaming, ray tracing, and ultra-fast SSD.",
        "category": "Electronics",
        "subcategory": "Gaming Consoles",
        "brand": "Sony",
        "price": 499.99,
        "original_price": 499.99,
        "currency": "USD",
        "attributes": {"storage": "825GB SSD", "resolution": "4K 120fps", "ray_tracing": "Yes"},
        "image_url": "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 15,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["gaming", "console", "playstation", "4k", "sony"]
    },
    {
        "title": "Nintendo Switch OLED Model",
        "description": "Hybrid gaming console with 7 inch OLED screen and enhanced audio.",
        "category": "Electronics",
        "subcategory": "Gaming Consoles",
        "brand": "Nintendo",
        "price": 349.99,
        "original_price": 349.99,
        "currency": "USD",
        "attributes": {"display": "7 inch OLED", "storage": "64GB", "modes": "TV + Handheld + Tabletop"},
        "image_url": "https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 30,
        "payment_options": ["full"],
        "tags": ["gaming", "console", "nintendo", "oled", "portable"]
    },
    {
        "title": "Xbox Series X Console",
        "description": "Most powerful Xbox ever with 12 teraflops of processing power.",
        "category": "Electronics",
        "subcategory": "Gaming Consoles",
        "brand": "Microsoft",
        "price": 499.99,
        "original_price": 499.99,
        "currency": "USD",
        "attributes": {"storage": "1TB SSD", "resolution": "4K 120fps", "game_pass": "Compatible"},
        "image_url": "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 18,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["gaming", "console", "xbox", "4k", "microsoft"]
    },
    {
        "title": "DJI Mini 4 Pro Drone",
        "description": "Compact drone with 4K/60fps video, obstacle avoidance, and 34 min flight time.",
        "category": "Electronics",
        "subcategory": "Drones",
        "brand": "DJI",
        "price": 759.00,
        "original_price": 759.00,
        "currency": "USD",
        "attributes": {"camera": "4K/60fps", "weight": "Under 249g", "flight_time": "34 minutes"},
        "image_url": "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 22,
        "payment_options": ["full", "installment_3", "installment_6"],
        "tags": ["drone", "4k", "portable", "obstacle-avoidance", "dji"]
    },
    {
        "title": "GoPro HERO12 Black",
        "description": "Waterproof action camera with 5.3K video, HyperSmooth 6.0, and HDR photo.",
        "category": "Electronics",
        "subcategory": "Cameras",
        "brand": "GoPro",
        "price": 399.99,
        "original_price": 399.99,
        "currency": "USD",
        "attributes": {"video": "5.3K 60fps", "stabilization": "HyperSmooth 6.0", "waterproof": "33ft"},
        "image_url": "https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 40,
        "payment_options": ["full"],
        "tags": ["action-camera", "4k", "waterproof", "stabilization", "gopro"]
    },
    {
        "title": "Bose QuietComfort Ultra Earbuds",
        "description": "Premium wireless earbuds with world-class noise cancellation and immersive audio.",
        "category": "Electronics",
        "subcategory": "Earbuds",
        "brand": "Bose",
        "price": 299.00,
        "original_price": 299.00,
        "currency": "USD",
        "attributes": {"anc": "World-Class", "audio": "Immersive Audio", "battery": "6 hours"},
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 45,
        "payment_options": ["full"],
        "tags": ["earbuds", "wireless", "anc", "immersive", "bose"]
    },
    {
        "title": "Marshall Stanmore III Bluetooth Speaker",
        "description": "Iconic rock-inspired speaker with rich, powerful sound and brass details.",
        "category": "Electronics",
        "subcategory": "Speakers",
        "brand": "Marshall",
        "price": 379.99,
        "original_price": 379.99,
        "currency": "USD",
        "attributes": {"connectivity": "Bluetooth 5.2", "power": "80W", "finish": "Black"},
        "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 30,
        "payment_options": ["full", "installment_3"],
        "tags": ["speaker", "bluetooth", "rock", "vintage", "marshall"]
    },
    {
        "title": "Canon EOS R6 Mark II Camera",
        "description": "Full-frame mirrorless camera with 24.2MP sensor and 40fps continuous shooting.",
        "category": "Electronics",
        "subcategory": "Cameras",
        "brand": "Canon",
        "price": 2499.00,
        "original_price": 2499.00,
        "currency": "USD",
        "attributes": {"sensor": "24.2MP Full-Frame", "video": "4K 60fps", "stabilization": "8-Stop IBIS"},
        "image_url": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 12,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["camera", "mirrorless", "full-frame", "4k", "canon"]
    },
    {
        "title": "LG C3 65-inch OLED TV",
        "description": "Award-winning OLED TV with perfect blacks, Dolby Vision, and webOS 23.",
        "category": "Electronics",
        "subcategory": "TVs",
        "brand": "LG",
        "price": 1796.99,
        "original_price": 2099.99,
        "currency": "USD",
        "attributes": {"size": "65 inches", "panel": "OLED evo", "refresh_rate": "120Hz"},
        "image_url": "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 15,
        "payment_options": ["full", "installment_6", "installment_12"],
        "tags": ["tv", "oled", "4k", "gaming", "lg"]
    },
    {
        "title": "Roku Streaming Stick 4K+",
        "description": "Powerful 4K HDR streaming with voice remote and hands-free control.",
        "category": "Electronics",
        "subcategory": "Streaming Devices",
        "brand": "Roku",
        "price": 49.99,
        "original_price": 49.99,
        "currency": "USD",
        "attributes": {"resolution": "4K HDR", "voice": "Hands-Free", "wifi": "Dual-Band"},
        "image_url": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 100,
        "payment_options": ["full"],
        "tags": ["streaming", "4k", "hdr", "voice-control", "roku"]
    },
    {
        "title": "Apple TV 4K (3rd Generation)",
        "description": "Premium streaming box with A15 Bionic chip, Dolby Vision, and Dolby Atmos.",
        "category": "Electronics",
        "subcategory": "Streaming Devices",
        "brand": "Apple",
        "price": 179.00,
        "original_price": 179.00,
        "currency": "USD",
        "attributes": {"chip": "A15 Bionic", "storage": "128GB", "hdr": "Dolby Vision + HDR10+"},
        "image_url": "https://images.unsplash.com/photo-1528928441742-b4ccac1bb04c?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 55,
        "payment_options": ["full"],
        "tags": ["streaming", "4k", "apple", "dolby-vision", "smart-home"]
    },
    {
        "title": "Nanoleaf Shapes Hexagon Starter Kit",
        "description": "Smart modular light panels with 16M+ colors, music sync, and voice control.",
        "category": "Electronics",
        "subcategory": "Smart Home",
        "brand": "Nanoleaf",
        "price": 199.99,
        "original_price": 199.99,
        "currency": "USD",
        "attributes": {"panels": "9 Hexagons", "colors": "16M+", "voice": "Alexa + Google + Siri"},
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
        "stock_status": "in_stock",
        "stock_quantity": 35,
        "payment_options": ["full"],
        "tags": ["smart-lights", "rgb", "modular", "voice-control", "nanoleaf"]
    }
]

def generate_id():
    return str(uuid.uuid4())

def add_timestamps(product):
    now = datetime.now()
    days_ago = random.randint(1, 90)
    created = now - timedelta(days=days_ago)
    updated = created + timedelta(days=random.randint(0, days_ago))
    
    product["id"] = generate_id()
    product["created_at"] = created.isoformat()
    product["updated_at"] = updated.isoformat()
    product["rating_avg"] = round(random.uniform(3.8, 5.0), 1)
    product["review_count"] = random.randint(10, 2500)
    return product

def merge_with_existing(new_products, output_file):
    existing = []
    if output_file.exists():
        with open(output_file, 'r', encoding='utf-8') as f:
            existing = json.load(f)
        print(f"Loaded {len(existing)} existing products")
    
    # Add timestamps to new products
    new_with_timestamps = [add_timestamps(p.copy()) for p in new_products]
    print(f"Generated {len(new_with_timestamps)} new products")
    
    # Merge
    all_products = existing + new_with_timestamps
    print(f"Total products: {len(all_products)}")
    
    return all_products

def save_to_json(products, output_file):
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(products, f, indent=2, ensure_ascii=False)
    print(f"Saved {len(products)} products to {output_file}")

if __name__ == "__main__":
    script_dir = Path(__file__).parent
    output_file = script_dir / "output" / "sample_products.json"
    
    all_products = merge_with_existing(BATCH3_PRODUCTS, output_file)
    save_to_json(all_products, output_file)
    
    # Print category distribution
    categories = {}
    for p in all_products:
        cat = p["category"]
        categories[cat] = categories.get(cat, 0) + 1
    
    print("\nCategory distribution:")
    for cat, count in sorted(categories.items()):
        print(f"  {cat}: {count}")
